### ISSUE TITLE
navigate to user profile page 

### ISSUE THREAD

**Issue by sandarenuDT** [HDLGenHub/HDLGenHub#48]
i need to show the detials of student and teacher seperatly by clicking their names in user profile. but its not working

**Comment by DulshanSiriwardhana** [comment]
![image](https://github.com/HDLGenHub/HDLGenHub/assets/85836178/2e19fc67-1e4f-44d9-870f-befd17a45114)

You should put ._id instead of .id

**Comment by DulshanSiriwardhana** [comment]
I fixed that and commited

**Comment by sandarenuDT** [comment]
but still the unable to see the user profile. appearing as user not found when navigate to user profile

**Comment by DulshanSiriwardhana** [comment]
I can see the User Profile is created only for teachers, and you are trying to get the role and id from useParams which parameters are passing through the route and it is not, because you only pass the id not the role.
