### ISSUE TITLE
student teacher fetch data

### ISSUE THREAD

**Issue by sandarenuDT** [HDLGenHub/HDLGenHub#56]
in network it is showing 200 but fetching data . there is an issue.

import { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import axios from 'axios';
// import './UserProfile.css'; // Ensure this path is correct

const UserProfile = () => {
    const { role, id } = useParams();
    const [user, setUser] = useState(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const fetchUser = async () => {
            try {
                let response;
                if (role === 'teacher') {
                    response = await axios.get(`http://localhost:4000/teacher/${id}`);
                } else if (role === 'student') {
                    response = await axios.get(`http://localhost:4000/student/${id}`);
                }
                setUser(response.data);
            } catch (error) {
                console.error('Error fetching user data:', error);
            } finally {
                setLoading(false);
                console.log("wdewf");
            }
        };

        fetchUser();
    }, [role, id]);

    if (loading) {
        return <div>Loading...</div>;
    }

    if (!user) {
        return <div>User not found</div>;
    }

    return (
        <div className="userProfileContainer">
            <div className="userProfile">
                <img src={user.profileImage} alt={`${user.name}'s profile`} />
                <h1>Name: {user.name}</h1>
                <p>Email: {user.email}</p>
                
                {role === 'teacher' && user.courses && (
                    <div>
                        <h2>Created Courses</h2>
                        <ul>
                            {user.courses.map(course => (
                                <li key={course._id}>{course.name}</li>
                            ))}
                        </ul>
                    </div>
                )}

                {role === 'student' && user.enrolledCourses && (
                    <div>
                        <h2>Enrolled Courses</h2>
                        <ul>
                            {user.enrolledCourses.map(course => (
                                <li key={course._id}>{course.name}</li>
                            ))}
                        </ul>
                    </div>
                )}

                {/* Add other user details as needed */}
            </div>
        </div>
    );
};

export default UserProfile;

**Comment by DulshanSiriwardhana** [comment]
![Uploading image.png…]()
/student
/teacher
should be started with capital letters

**Comment by DulshanSiriwardhana** [comment]
Problem is you didn't assign the role parameter, your are trying to get the role from the useParams. don't do that because you are already trying to pass the userid throgh the navigation route and trying to get the id using a react hook which is useParams and it is failed/i can see the undifined params (for the current state it is the teacher id), the easiest way is to store the role on local Storage when you clicked on a user, and then get the role when you need

**Comment by sandarenuDT** [comment]
can u check again. there is a problem with the route. @DulshanSiriwardhana

**Comment by sandarenuDT** [comment]
issue fixed
